import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ThemeProvider } from "@/components/theme-provider";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Telemetry Dashboard",
	description: "Generated by create next app",
};

// Conditionally import Service Worker only in production
const ServiceWorkerProvider =
	import.meta.env.MODE === "production"
		? require("../components/ServiceWorkerProvider").default
		: () => null;

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" suppressHydrationWarning>
			<body className={inter.className}>
				{import.meta.env.MODE === "production" && <ServiceWorkerProvider />}
				<ThemeProvider attribute="class" defaultTheme="system" enableSystem>
					{children}
				</ThemeProvider>
			</body>
		</html>
	);
}
