import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Telemetry Dashboard",
	description: "Generated by create next app",
};

// Conditionally import Service Worker only in production
const ServiceWorkerProvider = 
	process.env.NODE_ENV === 'production' 
		? require("../components/ServiceWorkerProvider").default 
		: () => null;

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={inter.className}>
				{process.env.NODE_ENV === 'production' && <ServiceWorkerProvider />}
				{children}
			</body>
		</html>
	);
}
