syntax = "proto3";
package pubSub;

import "google/protobuf/timestamp.proto";

option go_package = "github.com/OJPARKINSON/IRacing-Display/ingest/go/internal/messaging";

message Telemetry {
    string lap_id = 1;
    double speed = 2;
    double lap_dist_pct = 3;
    string session_num = 4;
    string session_type = 5;
    string session_name = 6;
    double session_time = 7;
    string track_name = 8;
    string track_id = 9;
    double steering_wheel_angle = 10;
    double player_car_position = 11;
    double velocity_x = 12;
    double velocity_y = 13;
    double velocity_z = 14;
    double fuel_level = 15;
    double throttle = 16;
    double brake = 17;
    double rpm = 18;
    double lat = 19;
    double lon = 20;
    uint32 gear = 21;
    double alt = 22;
    double lat_accel = 23;
    double long_accel = 24;
    double vert_accel = 25;
    double pitch = 26;
    double roll = 27;
    double yaw = 28;
    double yaw_north = 29;
    double voltage = 30;
    double lap_last_lap_time = 31;
    double water_temp = 32;
    double lap_delta_to_best_lap = 33;
    double lap_current_lap_time = 34;
    double l_fpressure = 35;
    double r_fpressure = 36;
    double l_rpressure = 37;
    double r_rpressure = 38;
    double l_ftemp_m = 39;
    double r_ftemp_m = 40;
    double l_rtemp_m = 41;
    double r_rtemp_m = 42;
    google.protobuf.Timestamp tick_time = 43;
}

message TelemetryBatch {
    repeated Telemetry records = 1;
    string batch_id = 2;
    string session_id = 3; 
    uint32 worker_id = 4;  
    google.protobuf.Timestamp timestamp = 5;
    string car_id = 6;
    string track_name = 7;
    string track_id = 8;
    string session_num = 9;
    string session_type = 10;
    string session_name = 11;
}