/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SessionIdRouteImport } from './routes/$sessionId'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NewSessionIdRouteImport } from './routes/new/$sessionId'

const SessionIdRoute = SessionIdRouteImport.update({
  id: '/$sessionId',
  path: '/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewSessionIdRoute = NewSessionIdRouteImport.update({
  id: '/new/$sessionId',
  path: '/new/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$sessionId': typeof SessionIdRoute
  '/new/$sessionId': typeof NewSessionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$sessionId': typeof SessionIdRoute
  '/new/$sessionId': typeof NewSessionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$sessionId': typeof SessionIdRoute
  '/new/$sessionId': typeof NewSessionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$sessionId' | '/new/$sessionId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$sessionId' | '/new/$sessionId'
  id: '__root__' | '/' | '/$sessionId' | '/new/$sessionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SessionIdRoute: typeof SessionIdRoute
  NewSessionIdRoute: typeof NewSessionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$sessionId': {
      id: '/$sessionId'
      path: '/$sessionId'
      fullPath: '/$sessionId'
      preLoaderRoute: typeof SessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new/$sessionId': {
      id: '/new/$sessionId'
      path: '/new/$sessionId'
      fullPath: '/new/$sessionId'
      preLoaderRoute: typeof NewSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SessionIdRoute: SessionIdRoute,
  NewSessionIdRoute: NewSessionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
